apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v0.16.0
        args: ["--dockerfile=Dockerfile",
               "--context=dir://var/jenkins_home/workspace/eTheatroJobs/Front/",
               "--destination=azamani/rps-game:latest",
               "--skip-tls-verify"]
        volumeMounts:
        - name: kaniko-secret
          mountPath: "/kaniko/.docker"
      restartPolicy: Never
      volumes:
      - name: kaniko-secret
        secret:
          secretName: rpskanikosec
          items:
          - key: .dockerconfigjson
            path: config.json