apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v0.16.0
        args: ["--dockerfile=Dockerfile",
               "--context=git://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@github.com/eTheatro/rps-game-fe.git#refs/heads/develop",
               "--destination=core.harbor.domain/games/rps-game:app_version",
               "--skip-tls-verify",
               "--insecure=true"]
        volumeMounts:
        - name: kaniko-secret
          mountPath: "/kaniko/.docker"
      restartPolicy: Never
      volumes:
      - name: kaniko-secret
        secret:
          secretName: rpskanikosec
          items:
          - key: .dockerconfigjson
            path: config.json