kind: Deployment
apiVersion: apps/v1
metadata:
  name: rps-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rps-game
  template:
    metadata:
      labels:
        app: rps-game
    spec:
      containers:
      - name: rps-game
        image: azamani/rps-game:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rps-game
  labels:
    app: rps-game
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: rps-game